GET http://localhost:5000/me

###

POST http://localhost:5000/event
Content-Type: application/json

{
  "eventName": "SALVARION",
  "description": "Kelima pendekar mengelilingi kota demi memusnahkan iblis?! Iblis yang memiliki mata pada sayapnya,dan tidak terkalahkan! Akankah mereka bisa menyelamatkan manusia dari iblis pembunuh itu? Saksikan perjuangan dan keseruan mereka hanya di Teater Bagol!",
  "price": "40000",
  "category": "THEATER",
  "place": "Dharma Negara Alaya, Denpasar, Bali",
  "link": "https://lynk.id/fiska/M1Nz6nx"
}

###
GET http://localhost:5000/users
###

POST http://localhost:5000/user
Content-Type: application/json

{
  "username": "test",
  "fullname": "Testing",
  "email": "test@gmail.com",
  "password": "123456",
  "confPassword": "123456",
  "role": "MITRA",
  "telephone": "081212341234"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "dom@gmail.com",
    "password": "123456"
}


###

DELETE http://localhost:5000/logout